//Authors table's rows
export const authorsArray = [
  {
    author_no: 1,
    author_name: 'Osama',
    university: 'Pecs',
    date_of_birth: '1990-07-23',
    mentor: 1,
    gender: 'm',
  },
  {
    author_no: 2,
    author_name: 'Mohammad',
    university: 'Pecs',
    date_of_birth: '1992-09-02',
    mentor: 1,
    gender: 'm',
  },
  {
    author_no: 3,
    author_name: 'Essam',
    university: 'Amsterdam',
    date_of_birth: '1996-05-22',
    mentor: 1,
    gender: 'm',
  },
  {
    author_no: 4,
    author_name: 'Marry',
    university: 'Damascus',
    date_of_birth: '1990-11-02',
    mentor: 1,
    gender: 'f',
  },
  {
    author_no: 5,
    author_name: 'Ali',
    university: 'Amsterdam',
    date_of_birth: '1990-09-21',
    mentor: 2,
    gender: 'm',
  },
  {
    author_no: 6,
    author_name: 'Lily',
    university: 'Amsterdam',
    date_of_birth: '1990-09-21',
    mentor: 2,
    gender: 'f',
  },
  {
    author_no: 7,
    author_name: 'Sara',
    university: 'Pecs',
    date_of_birth: '1990-09-21',
    mentor: 7,
    gender: 'f',
  },
  {
    author_no: 8,
    author_name: 'Hassan',
    university: 'Pecs',
    date_of_birth: '1990-09-21',
    mentor: 3,
    gender: 'm',
  },
  {
    author_no: 9,
    author_name: 'Nily',
    university: 'Pecs',
    date_of_birth: '1990-09-21',
    mentor: 5,
    gender: 'f',
  },
  {
    author_no: 10,
    author_name: 'Riad',
    university: 'Amsterdam',
    date_of_birth: '1993-01-20',
    mentor: 5,
    gender: 'm',
  },
  {
    author_no: 11,
    author_name: 'Nazek',
    university: 'Amsterdam',
    date_of_birth: '1990-02-19',
    mentor: 5,
    gender: 'f',
  },
  {
    author_no: 12,
    author_name: 'Abu',
    university: 'Damascus',
    date_of_birth: '1987-03-28',
    mentor: 5,
    gender: 'm',
  },
  {
    author_no: 13,
    author_name: 'Eshnit',
    university: 'Damascus',
    date_of_birth: '1982-05-02',
    mentor: 10,
    gender: 'f',
  },
  {
    author_no: 14,
    author_name: 'Viki',
    university: 'Damascus',
    date_of_birth: '1988-09-07',
    mentor: 10,
    gender: 'f',
  },
  {
    author_no: 15,
    author_name: 'Marry',
    university: 'Damascus',
    date_of_birth: '1990-11-02',
    mentor: 10,
    gender: 'f',
  },
];

//Research papers table's rows
export const researchPapersArray = [
  {
    paper_id: 1,
    paper_title: 'Databases',
    conference: 'Pecs conference',
    publish_date: '2020-06-20',
    h_index: 2,
  },
  {
    paper_id: 2,
    paper_title: 'AI',
    conference: 'Pecs conference',
    publish_date: '2020-08-20',
    h_index: 1,
  },
  {
    paper_id: 3,
    paper_title: 'Robotics',
    conference: 'Pecs conference',
    publish_date: '2021-06-20',
    h_index: 5,
  },
  {
    paper_id: 4,
    paper_title: 'Image processing',
    conference: 'Pecs conference',
    publish_date: '2022-07-20',
    h_index: 5,
  },
  {
    paper_id: 5,
    paper_title: 'nature',
    conference: 'Damascus conference',
    publish_date: '2021-06-20',
    h_index: 7,
  },
  {
    paper_id: 6,
    paper_title: 'trees',
    conference: 'Damascus conference',
    publish_date: '2020-01-05',
    h_index: 4,
  },
  {
    paper_id: 7,
    paper_title: 'Fields and farming',
    conference: 'Damascus conference',
    publish_date: '2019-01-20',
    h_index: 8,
  },
  {
    paper_id: 8,
    paper_title: 'English studies',
    conference: 'Pecs conference',
    publish_date: '2020-04-05',
    h_index: 3,
  },
  {
    paper_id: 9,
    paper_title: 'English for kids',
    conference: 'Pecs conference',
    publish_date: '2021-06-20',
    h_index: 2,
  },
  {
    paper_id: 10,
    paper_title: 'Basics of starting',
    conference: 'Pecs conference',
    publish_date: '2019-08-20',
    h_index: 5,
  },
  {
    paper_id: 11,
    paper_title: 'CARS',
    conference: 'Amsterdam conference',
    publish_date: '2022-07-20',
    h_index: 36,
  },
  {
    paper_id: 12,
    paper_title: 'F1',
    conference: 'Amsterdam conference',
    publish_date: '2022-07-20',
    h_index: 2,
  },
  {
    paper_id: 13,
    paper_title: 'Rich fish',
    conference: 'Amsterdam conference',
    publish_date: '2018-05-20',
    h_index: 3,
  },
  {
    paper_id: 14,
    paper_title: 'Ocean',
    conference: 'Amsterdam conference',
    publish_date: '2022-06-20',
    h_index: 4,
  },
  {
    paper_id: 15,
    paper_title: 'Database for everyone',
    conference: 'Amsterdam conference',
    publish_date: '2020-06-20',
    h_index: 5,
  },
  {
    paper_id: 16,
    paper_title: 'C++',
    conference: 'Pecs conference',
    publish_date: '2021-06-20',
    h_index: 6,
  },
  {
    paper_id: 17,
    paper_title: 'Java',
    conference: 'Pecs conference',
    publish_date: '2018-09-20',
    h_index: 7,
  },
  {
    paper_id: 18,
    paper_title: 'Python',
    conference: 'Pecs conference',
    publish_date: '2018-06-20',
    h_index: 8,
  },
  {
    paper_id: 19,
    paper_title: 'Tigers in jangles',
    conference: 'Amsterdam conference',
    publish_date: '2021-08-05',
    h_index: 9,
  },
  {
    paper_id: 20,
    paper_title: 'Math for basis',
    conference: 'Amsterdam conference',
    publish_date: '2020-01-25',
    h_index: 2,
  },
  {
    paper_id: 21,
    paper_title: 'Since',
    conference: 'Amsterdam conference',
    publish_date: '2017-11-20',
    h_index: 1,
  },
  {
    paper_id: 22,
    paper_title: 'Easy math',
    conference: 'Amsterdam conference',
    publish_date: '2015-06-20',
    h_index: 2,
  },
  {
    paper_id: 23,
    paper_title: 'Sin and Cos',
    conference: 'Amsterdam conference',
    publish_date: '2021-02-27',
    h_index: 3,
  },
  {
    paper_id: 24,
    paper_title: 'Areas',
    conference: 'Amsterdam conference',
    publish_date: '2020-06-20',
    h_index: 4,
  },
  {
    paper_id: 25,
    paper_title: 'Bi values',
    conference: 'Pecs conference',
    publish_date: '2013-06-24',
    h_index: 5,
  },
  {
    paper_id: 26,
    paper_title: 'eyes beauty',
    conference: 'Damascus conference',
    publish_date: '2021-04-22',
    h_index: 6,
  },
  {
    paper_id: 27,
    paper_title: 'Body secrets',
    conference: 'Damascus conference',
    publish_date: '2020-06-20',
    h_index: 7,
  },
  {
    paper_id: 28,
    paper_title: 'Healthy life',
    conference: 'Damascus conference',
    publish_date: '2019-07-23',
    h_index: 8,
  },
  {
    paper_id: 29,
    paper_title: 'Food routines',
    conference: 'Damascus conference',
    publish_date: '2020-02-24',
    h_index: 9,
  },
  {
    paper_id: 30,
    paper_title: 'Happier life with vegetables',
    conference: 'Damascus conference',
    publish_date: '2015-05-15',
    h_index: 3,
  },
];

//Author research table's rows
export const authorsResearchArray = [
  {
    author_no: 1,
    paper_id: 1,
  },
  {
    author_no: 1,
    paper_id: 2,
  },
  {
    author_no: 1,
    paper_id: 3,
  },
  {
    author_no: 1,
    paper_id: 4,
  },
  {
    author_no: 2,
    paper_id: 5,
  },
  {
    author_no: 3,
    paper_id: 6,
  },
  {
    author_no: 4,
    paper_id: 6,
  },
  {
    author_no: 5,
    paper_id: 7,
  },
  {
    author_no: 6,
    paper_id: 1,
  },
  {
    author_no: 13,
    paper_id: 28,
  },
  {
    author_no: 14,
    paper_id: 28,
  },
  {
    author_no: 15,
    paper_id: 29,
  },
  {
    author_no: 15,
    paper_id: 30,
  },
];
